spring:
  profiles:
    active: development
  datasource:
    primary:
      testOnBorrow: true
      validationQuery: SELECT 1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        generate_statistics: false
        id.new_generator_mappings: true
        order_updates: true
        default_batch_fetch_size: 4
        max_fetch_depth: 2
flyway:
  enabled: false
  primary: 
    location: classpath:db/migration/primary
  secondary:
    location: classpath:db/migration/secondary
dianxiao:
    record:
        directory: /usr/share/record/pbxrecord
    target:
        directory: /opt/tmk/record

