spring:
  datasource:
    primary:
      initialize: false
      url: jdbc:mysql://localhost:3306/A002?useUnicode=yes&characterEncoding=gbk
      username: root
      password: 0ffs4t?
      driver-class-name: com.mysql.jdbc.Driver
    secondary:
      initialize: false
      url: jdbc:h2:mem:secondary
      username: sa
      password:
      driver-class-name: org.h2.Driver
